repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --config .\Recipes_app\.flake8
        language: system
        types: [python]
        pass_filenames: false