services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/recipes_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database
  database:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
