name: Django CI/CD for
on:
  push:
    branches: [ "main",]
  pull_request:
    branches: [ "main",]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install flake8
    - name: Test with flake8
      run:
        python -m  flake8
    - name: Build and run containers
      run:
        docker-compose up -d --build